name: log_dispatcher
description: "A package for handling and dispatching error logs from Flutter applications and server requests."
version: 1.0.0
homepage: https://github.com/Imron-Code17
repository: https://github.com/Imron-Code17/log_dispatcher

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:



 
